export const SIGNIN = 'SIGNIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';

export const SIGNOUT = 'SIGNOUT';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_ERROR = 'SIGNOUT_ERROR';

export const GET_MEMBER_DETAILS = 'GET_MEMBER_DETAILS';
export const GET_MEMBER_DETAILS_SUCCESS = 'GET_MEMBER_DETAILS_SUCCESS';
export const GET_MEMBER_DETAILS_ERROR = 'GET_MEMBER_DETAILS_ERROR';

export const GET_GROUPS = 'GET_GROUPS';
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS';
export const GET_GROUPS_ERROR = 'GET_GROUPS_ERROR';
export const GET_GROUPS_LOADING = 'GET_GROUPS_LOADING';

export const GET_CHAMPIONSHIP = 'GET_CHAMPIONSHIP';
export const GET_CHAMPIONSHIP_SUCCESS = 'GET_CHAMPIONSHIP_SUCCESS';
export const GET_CHAMPIONSHIP_ERROR = 'GET_CHAMPIONSHIP_ERROR';
export const GET_CHAMPIONSHIP_LOADING = 'GET_CHAMPIONSHIP_LOADING';

export const GET_GAME = 'GET_GAME';
export const GET_GAME_SUCCESS = 'GET_GAME_SUCCESS';
export const GET_GAME_ERROR = 'GET_GAME_ERROR';
export const GET_GAME_LOADING = 'GET_GAME_LOADING';

export const ADD_OPTION = 'ADD_OPTION';
export const ADD_OPTION_SUCCESS = 'ADD_OPTION_SUCCESS';
export const REMOVE_OPTION = 'REMOVE_OPTION';
export const REMOVE_OPTION_SUCCESS = 'REMOVE_OPTION_SUCCESS';

export const OPEN_TOAST = 'OPEN_TOAST';
export const CLOSE_TOAST = 'CLOSE_TOAST';
