export const SIGNIN = 'SIGNIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';

export const SIGNOUT = 'SIGNOUT';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_ERROR = 'SIGNOUT_ERROR';

export const GET_MEMBER_DETAILS = 'GET_MEMBER_DETAILS';
export const GET_MEMBER_DETAILS_SUCCESS = 'GET_MEMBER_DETAILS_SUCCESS';
export const GET_MEMBER_DETAILS_ERROR = 'GET_MEMBER_DETAILS_ERROR';

export const GET_GROUPS = 'GET_GROUPS';
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS';
export const GET_GROUPS_ERROR = 'GET_GROUPS_ERROR';
export const GET_GROUPS_LOADING = 'GET_GROUPS_LOADING';

export const GET_CHAMPIONSHIP = 'GET_CHAMPIONSHIP';
export const GET_CHAMPIONSHIP_SUCCESS = 'GET_CHAMPIONSHIP_SUCCESS';
export const GET_CHAMPIONSHIP_ERROR = 'GET_CHAMPIONSHIP_ERROR';
export const GET_CHAMPIONSHIP_LOADING = 'GET_CHAMPIONSHIP_LOADING';

export const GET_GAME = 'GET_GAME';
export const GET_GAME_SUCCESS = 'GET_GAME_SUCCESS';
export const GET_GAME_ERROR = 'GET_GAME_ERROR';
export const GET_GAME_LOADING = 'GET_GAME_LOADING';
export const GET_GAMES_BY_DATE = 'GET_GAMES_BY_DATE';
export const GET_GAMES_BY_DATE_SUCCESS = 'GET_GAMES_BY_DATE_SUCCESS';
export const GET_GAMES_BY_DATE_ERROR = 'GET_GAMES_BY_DATE_ERROR';
export const GET_GAMES_BY_DATE_LOADING = 'GET_GAMES_BY_DATE_LOADING';

export const ADD_OPTION = 'ADD_OPTION';
export const ADD_OPTION_SUCCESS = 'ADD_OPTION_SUCCESS';
export const REMOVE_OPTION = 'REMOVE_OPTION';
export const REMOVE_OPTION_SUCCESS = 'REMOVE_OPTION_SUCCESS';
export const SET_BET_VALUE = 'SET_BET_VALUE';
export const SET_NAME = 'SET_NAME';
export const PLACE_BET = 'PLACE_BET';
export const PLACE_BET_LOADING = 'PLACE_BET_LOADING';
export const PLACE_BET_SUCCESS = 'PLACE_BET_SUCCESS';
export const PLACE_BET_ERROR = 'PLACE_BET_ERROR';
export const CLEAR_BET = 'CLEAR_BET';

export const CLEAR_PENDING_BET = 'CLEAR_PENDING_BET';
export const GET_PENDING_BET = 'GET_PENDING_BET';
export const GET_PENDING_BET_LOADING = 'GET_PENDING_BET_LOADING';
export const GET_PENDING_BET_SUCCESS = 'GET_PENDING_BET_SUCCESS';
export const GET_PENDING_BET_ERROR = 'GET_PENDING_BET_ERROR';
export const CONFIRM_PENDING_BET = 'CONFIRM_PENDING_BET';
export const CONFIRM_PENDING_BET_LOADING = 'CONFIRM_PENDING_BET_LOADING';
export const CONFIRM_PENDING_BET_SUCCESS = 'CONFIRM_PENDING_BET_SUCCESS';
export const CONFIRM_PENDING_BET_ERROR = 'CONFIRM_PENDING_BET_ERROR';

export const OPEN_TOAST = 'OPEN_TOAST';
export const CLOSE_TOAST = 'CLOSE_TOAST';

export const CLEAR_TICKET = 'CLEAR_TICKET';
export const GET_TICKET = 'GET_TICKET';
export const GET_TICKET_SUCCESS = 'GET_TICKET_SUCCESS';
export const GET_TICKET_ERROR = 'GET_TICKET_ERROR';
export const GET_TICKET_LOADING = 'GET_TICKET_LOADING';
export const SET_TICKET_RESULT = 'SET_TICKET_RESULT';
export const SET_TICKET_RESULT_ERROR = 'SET_TICKET_RESULT_ERROR';
export const SET_TICKET_RESULT_LOADING = 'SET_TICKET_RESULT_LOADING';

export const GET_CONFIRMED_BETS = 'GET_CONFIRMED_BETS';
export const GET_CONFIRMED_BETS_LOADING = 'GET_CONFIRMED_BETS_LOADING';
export const GET_CONFIRMED_BETS_SUCCESS = 'GET_CONFIRMED_BETS_SUCCESS';
export const GET_CONFIRMED_BETS_ERROR = 'GET_CONFIRMED_BETS_ERROR';

export const GET_PENDING_TICKETS = 'GET_PENDING_TICKETS';
export const GET_PENDING_TICKETS_LOADING = 'GET_PENDING_TICKETS_LOADING';
export const GET_PENDING_TICKETS_SUCCESS = 'GET_PENDING_TICKETS_SUCCESS';
export const GET_PENDING_TICKETS_ERROR = 'GET_PENDING_TICKETS_ERROR';

export const GET_MEMBERS = 'GET_MEMBERS';
export const GET_MEMBERS_LOADING = 'GET_MEMBERS_LOADING';
export const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS';
export const GET_MEMBERS_ERROR = 'GET_MEMBERS_ERROR';
